Update symfonytodo.yml

diff --git a/.github/workflows/symfonytodo.yml b/.github/workflows/symfonytodo.yml
--- a/.github/workflows/symfonytodo.yml
+++ b/.github/workflows/symfonytodo.yml
@@ -64,17 +64,18 @@ jobs:
           sudo mv ~/.symfony/bin/symfony /usr/local/bin/symfony
         
  
-     # - name: Run Migration
-      #  run: |
-       #   composer require --dev symfony/orm-pack
-        #  php bin/console doctrine:schema:update --force || echo "schema update failed"
-        #env:
-         # DATABASE_URL: mysql://root:@127.0.0.1:3306/todoapp?serverVersion=mariadb-10.4.21
+      - name: Run Migration
+        run: |
+          composer require --dev symfony/orm-pack
+          php bin/console doctrine:schema:update --force || echo "schema update failed"
+        env:
+          DATABASE_URL: mysql://root:@127.0.0.1:3306/todoapp?serverVersion=mariadb-10.4.21
         
-      #- name: Server start
-       # run: php bin/console server:start 127.0.0.1:8000
+      - name: Server start
+        run: |
+          symfony server:start -d
+          symfony open:local
         
-          
       #- name: Run Unit tests
        # run: php bin/phpunit tests/TaskTodoTest.php
       
